### ISSUE TITLE
Перетаскивание книжных полок

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#10]
Сделать возможность перетаскивания книжные полки в режиме их редактирования, чтобы можно было настроить их последовательность «под себя». Сейчас при их создании они располагаются отсортированными по алфавиту.

**Comment by kolyvan** [comment]
Ответ такой же как и на вопрос почему нельзя переименовывать папки. А оно  действительно надо кому то кроме двух-трех человек? KyBook не файловый менеджер и облегчить работу с папками не является его целью.
