### ISSUE TITLE
Баг при прокрутке

### ISSUE THREAD

**Issue by doublei13** [kolyvan/kybook#100]
Добрый день! Видео (посмотрите до конца) с багом прикрепил (при перезапуске приложения, страницы восстанавливаются). Кроме этого, очень часто приложение вылетает при таком дёргании ползунка.
iPad 2017
iOS 12.1
[2018-11-28 11.47.11.zip](https://github.com/kolyvan/kybook/files/2623891/2018-11-28.11.47.11.zip)

**Comment by kolyvan** [comment]
Простите а почему Вы решили что что баг?

В видео вы очень часто-часто меняете позицию чтения в PDF документе. 
KyBook через некоторое время начинает неуспевать отрисовывать страницы, очередь на отрисовку постоянно увеличивается, памяти приложению требуется все больше и больше (приложение не успевает и не может освободить память страниц в очереди на отрисовку). Через некоторое время в результате Ваших действий, памяти перестает хватать или же приложение превышает лимит на время процессора которое ему предоствила iOS. 

Далее iOS при наступлении или нехватки памяти или перегрузки процессора - закрывает приложение. Это называется - DDOS (атака типа отказ в обслуживании). 
Поздравляю - Вы только что собственноручно отддосили свой iPad. 

Точно также можно вырубить ПК начав непрерывно открывать большие документы.  Рано или поздно Ваш ПК замедлится и перестанет отзываться. На мобильных устройствах ресурсы ограничены несравненно сильнее и условия  работы приложений несравненно строже. iOS гораздо быстрее закрывает любое приложение которое начинает неразумно потреблять память или такты процессора.

Наверно можно поставить некоторую защиту от вандальских действий пользователя, ввести некие ограничения на максимальный размер очереди страниц на отрисовку или ограничения частоты смены страниц через полузнок. Но скорее всего это только ухудшит комфорт нормальных пользователей но полностью не сможет предотвратить ненормальные действия.

**Comment by doublei13** [comment]
Я же не просто так начал это делать. Я читал книгу и решил просто пролистать (не так как на видео) и приложение вылетело. Сейчас опять пролистал как обычный пользователь листает книги. Опять вилетело. Это ненормальная ситуация для приложения. В других приложениях я тоже вполне обычно пролистывал книги и ничего не вылетало. Извините, конечно, но нужно оптимизировать тогда приложение, а не винить пользователя. Записать тот момент, когда вылетает приложение не получилось, так как сразу отключается запись с экрана без сохранения видеозаписи.

Решение проблемы: при перемещении ползунка не отрисовывать страницы, а изменять label с номером страницы. Как только пользователь закончил перемещение, остановился и отпустил ползунок, отрисовать одну(!) страницу. Мне, например, нужно попасть на определенную страницу. Я перемещаю ползунок и попадаю. Промежуточные результаты, когда я прокручиваю ползунок мне не нужны. И память потреблять не будет. Такой сценарий уже реализован в одной из популярных читалок. Это гораздо удобнее, чем вводить номер страницы (кстати, такой фичи нет в этом приложении, но и не надо).

Я сам разработчик, поэтому понимаю ваше негодование. Но я даже не пытался тестировать приложение, я просто пролистал. “Защита от дурака” тоже должна быть. Но в данном случае нужно просто оптимизировать и не использовать ресурсы просто так.

**Comment by doublei13** [comment]
Поправочка. Изменять не только label с номером, но и с названием раздела внизу, чтобы можно было сориентироваться, где мы находимся.

**Comment by kolyvan** [comment]
Для разработчика я тогда немного поподробнее.

> 
> В основном главная причина всех проблем с PDF, это переход с PDFIUM (Chrome) на PDFKit от Apple. PDFIUM несравненно стабильнее по сравнению с framework-от от Apple , но собрать и поддерживать его под iOS нереальная боль и кроме того он очень-очень большой (часть хрома как никак). К сожалению в KyBook 3 переход на PDFKit показал что некоторые PDF-ки не дружат с Apple PDFkit.
>  ....

В общем всё нет так, причина была в недоработке моего кода.

**Comment by kolyvan** [comment]
И если Вас не затруднит, то не могли бы Вы поделиться ссылкой на этот PDF файл чтобы я смог протестировать на своих устройствах? Заранее спасибо.

**Comment by doublei13** [comment]
Спасибо за подробное разъяснение, теперь все понятно. В принципе, это не самая важная для меня проблема, можно пользоваться содержанием.

И отдельная благодарность за вкладки как в браузере и за гугл-переводчик, прешедший на смену яндекс-переводчика. Гугл качественно переводит, полезная штука, иногда приходится пользоваться. Это тот функционал, которого нет у других читалок. 

Ещё одна деталь, по поводу pdf. Во второй версии приложения, когда выделял фрагмент текста и переводил, оно как бы копировало кусками по строчке и отдельно переводило по строчке. Из-за этого перевод был некорректен, вырван из контекста, переводило не по предложению, а по строке. Не знаю в чем была причина. Либо это читалка pdf кусками отдавала, либо это такой яндекс-переводчик. Но в третьей версии все хорошо с этим и переводит корректно. Но это такое, просто хотелось бы, чтобы на это обратили внимание при переписании кода. PDF везде один и тот же (так как это не скан, а ebook in pdf):
https://www.google.com/search?q=lock+andrew+asp.net+core+in+action+pdf

**Comment by kolyvan** [comment]
Исправлено в бете v0.6.4
Очень большое спасибо за сообщение о проблеме.
