### ISSUE TITLE
Несколько предложений для Pro версии.

### ISSUE THREAD

**Issue by shell1986** [kolyvan/kybook#101]
Константин привет, вчера купил про для 3 версии и у меня родилось несколько предложений.
1 отображение информации о планшете в режиме полного экрана.
В режиме полного экрана отображаются только часы, иногда это не очень удобно, очень важно знать сколько осталось заряда, есть ли сеть и тд особенно когда ты в поезде. Предлагаю вариативно это добавить.

2 Отдельно настроить отступ главы, незнаю как другим но настройку вертикального отсупа главы более приятны и аутентичны. 

3 Отдельно настроить отступ левой и правой стороны. 
С учетом современной тенденции сужения краев, было бы сдорово иметь такую возможность.

4 Возможность отключить пароль для wifi облака. Это конечно мелочь, но иногда неудобно вводить пароль что бы загрузить книжку, было бы здорово что бы была возможность его отключить. А например более маниакальным господам была возможность настроить более сложный пароль. 

5 Возможность сделать дизайн оформления на основе текущих шаблонов. 

Спасибо за вашу работу.

**Comment by kolyvan** [comment]
> В режиме полного экрана отображаются только часы, иногда это не очень удобно, очень важно знать сколько осталось заряда, есть ли сеть и тд особенно когда ты в поезде

Для того чтобы получить информацию о заряде батареи достаточно сделать одно нажатие. Для размещения же индикатора заряда на экране чтения к сожалению нет места.

> Отдельно настроить отступ главы
> Отдельно настроить отступ левой и правой стороны

Вы можете это сделать через настройки книги, смотрите приложенный снимок экрана.

![kybook-ebook-settings](https://user-images.githubusercontent.com/791320/49198833-d8c7d980-f3e0-11e8-95ce-5c6a4f9517f7.png)


> Возможность отключить пароль для wifi облака

Вы о контент-сервере?
К сожалению я не могу выполнить Вашу просьбу. Отключение пароля небезопасно. К тому же, как правило, ваш браузер может предложить запомнить пароль и ввести его Вам будет достаточно всего один раз.

> Возможность сделать дизайн оформления на основе текущих шаблонов.

Простите, к сожалению я не совсем понимаю о чем идет речь. Вы не могли бы более подробно описать свое предложение?

**Comment by shell1986** [comment]
> Для того чтобы получить информацию о заряде батареи достаточно сделать одно нажатие. Для размещения же индикатора заряда на экране чтения к сожалению нет места.

В колонтитулах места предостаточно, что внизу, что вверху.

> Вы можете это сделать через настройки книги, смотрите приложенный снимок экрана.

В настройках книги нету настройки отступа главы. Абзац и глава разные вещи. 

В настройках нет возможности отдельно сделать отступ в одной из сторон, только одновременно на две стороны.

> К сожалению я не могу выполнить Вашу просьбу. Отключение пароля небезопасно. 

Вас не просят убрать эту функцию, вас просят дать возможность ее отключать. Пусть пользователь сам решает что ему безопасно, а что нет. 

> Простите, к сожалению я не совсем понимаю о чем идет речь. Вы не могли бы более подробно описать свое предложение?

При создании нового шаблона, я бы хотел взять за основу уже имеющейся и поменять в нем пару цветов. 

PS Судя по вашим ответам я понял что после оплаты про пользователь вам не интересен. Типичный русский подход. Всего доброго.

**Comment by kolyvan** [comment]
> Типичный русский подход

Ох, не будь ты расистом я бы объяснил как можно поменять цвета, но слава богу успел этого не сделать.

**Comment by shell1986** [comment]
> Ох, не будь ты расистом я бы объяснил как можно поменять цвета, но слава богу успел этого не сделать.

Во первых я не расист, да думаю мы с вами одного цвета кожи. 

**Нацисткий бред который запостил сюда @supersh86  был удален мной, @kolyvan.*

**Comment by kolyvan** [comment]
> какой у вас нетипичный русккий подход.

В сети полно твоих единомышленников, прекращай  уже постить здесь свой тупой наци бред. 

> Во первых я не расист, да думаю мы с вами одного цвета кожи.

Ой, ды ты еще и полу-образованный расист.

**Comment by shell1986** [comment]
> > какой у вас нетипичный русккий подход.
> 
> В сети полно твоих единомышленников, прекращай уже постить здесь свой тупой наци бред.
> 
> > Во первых я не расист, да думаю мы с вами одного цвета кожи.
> 
> Ой, ды ты еще и полу-образованный расист.

Как мне вернуть деньги за pro версию? Я лучше куплю другую программу. Для справочки советую почитать статью в википедии о расизме. 

Ps. То что вы так боязно трете чужие комменты не делает вам чести. Я разочаровался в вас как в производителе программного обеспечения.

**Comment by kolyvan** [comment]
> То что вы так боязно трете чужие комменты не делает вам чести

Не все готовы терпеть гостя, который с порога зигует, портит воздух и поет хорст вессель. Вот такая жизнь, приходится гостя вон и убирать за ним.

> Я разочаровался в вас как в производителе программного обеспечения.

Ох, как мне жить, наци скам меня не оценил.

> Как мне вернуть деньги за pro версию? 

Пиши в спортлото, может там поймут твою тонкую арийскую душу обиженную русским быдлом.

> Для справочки советую почитать статью в википедии о расизме.

Дай угадаю, ЕГЭ поколение? Впрочем, это был риторический вопрос, не отвечай пожалуйста.
На всякий случай повторю еще раз, **не надо сюда больше писать**, таких как ты тут не любят.

**Comment by supersh86** [comment]
> Не все готовы терпеть гостя, который с порога зигует, портит воздух и поет хорст вессель. Вот такая жизнь, приходится гостя вон и убирать за ним.

Ни кто не зигует и не поет нациские гимны. Вам просто указали что вы плохо относитесь к своим клиентам.

> Пиши в спортлото, может там поймут твою тонкую арийскую душу обиженную русским быдлом.

Во первых в данном диалоге ведете себя как быдло именно вы, оскорбляйте человека который купил вашу программу, вешайте на него ярлыки, и называйте расистом и фашистом, хотя он этого не заслуживает. 

> Дай угадаю, ЕГЭ поколение? Впрочем, это был риторический вопрос, не отвечай пожалуйста.
> На всякий случай повторю еще раз, не надо сюда больше писать, таких как ты тут не любят.

Вопрос риторический, но я отвечу. Нет, я не сдавал ЕГЭ и в отличии от вас знаю что такое расизм, фашизм и нацизм.
Мне вот интересно, когда вас критикуют вы всех называйте расистами? У вашей программы достаточно негативных отзывов, их тоже оставили нацисты которые зигуют? Мне кажется что я общаюсь с глупым ребенком нежели со взрослым человеком.

Я буду писать сколько хочу, потому как я купил вашу программу и являюсь вашим клиентом. А с клиентами, так не разговаривают на гитхабе.

Жду ваших извинений.
