### ISSUE TITLE
Добавление в закладки

### ISSUE THREAD

**Issue by doublei13** [kolyvan/kybook#102]
Небольшой косметический баг:
0. В книге нет закладок.
1. На любой странице нажимаем кнопку добавления в закладки (справа внизу).
2. Открываем меню Закладки (... => Закладки).
3. Закладка добавилась, но присутствует надпись посредине “Нет закладок”.
4. Закрываем меню и повторяем шаг 1-3. Та же надпись, только уже закладок не одна, а две.

При добавлении закладки через меню закладок (Закладки => плюсик в внизу слева) все нормально работает и надпись исчезает.

Не знаю, как на других устройствах, но на iPad так.

**Comment by doublei13** [comment]
Перегрузил приложение, стало нормально, прошу прощения

**Comment by doublei13** [comment]
При перезагрузке пропало, поспешил, закрыл тему. Оказалось вот после чего такое:
0. В книге нет закладок.
1. На любой странице нажимаем кнопку добавления в закладки (справа внизу).
2. Открываем меню Закладки (... => Закладки).
3. Удаляем закладку, закрываем меню закладок.
4. На любой странице нажимаем кнопку добавления в закладки (справа внизу).
5. Открываем меню Закладки (... => Закладки).
6. Закладка добавилась, но присутствует надпись посредине “Нет закладок”. Теперь при любых манипуляциях с закладками, вне зависимости от того, сколько мы добавляем закладок, будет присутствовать эта надпись.

Обобщу. Это начинает все происходить после удаления последней(!) вкладки.

**Comment by kolyvan** [comment]
Спасибо за сообщение о проблеме.

**Comment by kolyvan** [comment]
Fixed in beta v0.6.5
