### ISSUE TITLE
Cosmetic: wrong label in Search settings

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#104]
KyBook 3 v0.6.6 | #132

1. Tap `Search`
2. Tap `Library`
3. Tap the settings icon
4. Label says 'Library'
5. Tap `Close`
6. Tap `Internet`
7. Tap the settings icon
8. Label says 'Library'
9. Tap `Close`
10. Tap `Catalogs`
11. Tap the settings icon
12. Label says 'Catalogs'

Presumably, the label at 8. is wrong.

**Comment by kolyvan** [comment]
Thank you much for the bug report.

**Comment by kolyvan** [comment]
Fixed in beta build 134 v0.6.7
