### ISSUE TITLE
Cosmetic: on iPhone X, home bar always visible

### ISSUE THREAD

**Issue by cunningjames** [kolyvan/kybook#105]
Using KyBook 3 on an iPhone X, I can’t help but notice that the home bar remains visible at all times. That can be a little distracting in an ebook reader, and some apps do hide the bar. Would it be possible to add this functionality?

(For what it’s worth, this very issue is what caused me to look for an alternative to Marvin in the first place, which feels like it may be dead at this point ...)

**Comment by kolyvan** [comment]
Sorry no.

**Comment by cunningjames** [comment]
Well, fair enough! Thanks for the response. My quest for a great (and active) ebook reader will continue.

**Comment by karlic** [comment]
@cunningjames please stick with KyBook 3, it really is a great reader and is still improving. @kolyvan can seem a bit abrupt and seems to like saying no to things he later implements. :-)

In the meantime, does this help? 
https://youtu.be/tbuyYWv1JLw
