### ISSUE TITLE
Нет скидки.

### ISSUE THREAD

**Issue by ArinaLikholet** [kolyvan/kybook#107]
Здравствуйте. Я покупала 2 прошлые версии KyBook. В ответах в апсторе вы написали, что для тех, кто уже купил прошлые версии ПРО версия будет стоить 100руб. Сейчас в приложении стоимость версии ПРО 299руб. Как получить скидку?

**Comment by kolyvan** [comment]
Для получения скидки необходимо чтобы в **KyBook 2** была активирована Про покупка в приложении.

> ПРО версия будет стоить 100руб.

В настоящий момент улучшение до Про со скидкой стоит 149руб.
