### ISSUE TITLE
Kybook3 can’t connect to my local OPDS (calibre) - kybook 2 can!

### ISSUE THREAD

**Issue by JulianSatran** [kolyvan/kybook#108]
somewhat dissapointed by the regression

**Comment by JulianSatran** [comment]
?.

**Comment by karlic** [comment]
I’ve connected KyBook 3 to calibre and transferred >500 books, so there is no “regression”. If you’d like help, you’ll need to provide more information—start with the info suggested here: 
http://kybook-reader.com/faq/2018/10/08/raise_an_issue.html

**Comment by JulianSatran** [comment]
You can check it by yourself. I will leave the library open for 2 hours.
The libraries are accessible in the browser and Kybook 2.
http://JuloHome.satran.net:1357
I am using and iPad  - 12.1.1,  Kybook v0.6.8|#138

**Comment by JulianSatran** [comment]
And to some your comments may look abrasive. The first line is definitely not adding anything to the dialog.

**Comment by JulianSatran** [comment]
OK - IT doesn't look like you did try. Please let me know when you want to try and will open you the server. And BTW your phone version will not apply the pro feature I bought on the iPad. Is a bug or you expect a subscription for each device?

**Comment by kolyvan** [comment]
@JulianSatran, please provide additional info.
At least the full error message (or screenshot)

But anyway, failure to connect to some site in the Internet is nothing extraordinary. It's Internet, there are always some troubles may occurs.

**Comment by kolyvan** [comment]
@JulianSatran,  please be patient and do not offense other users. @karlic wrote the absolute truth, you need provide more details about this issue. Nobody can help without any information.

**Comment by kolyvan** [comment]
> http://JuloHome.satran.net:1357

Your URL seems are invalid. 
Most likely, did you use Calibre content-server, yes?
The typical Calibre content server provides OPDS catalog at /opds path.
When you added OPDS catalog with this URL 'http://JuloHome.satran.net:1357', Kybook offers to use a valid form  - http://JuloHome.satran.net:1357/opds . Please carefully read all KyBook messages.

I can't say more without credentials but seems  your OPDS catalog is accessible by correct URL http://JuloHome.satran.net:1357/opds .

![kybook-opds-calibre-fix](https://user-images.githubusercontent.com/791320/50437490-a654c200-0935-11e9-867f-dd63eb33c895.png)

**Comment by JulianSatran** [comment]
OK - it works but Kybook2 did not need the opds part

**Comment by kolyvan** [comment]
> OK - it works but Kybook2 did not need the opds part

Sorry, but you are wrong. 
KyBook 2 does the same URL check and offers alter URL like KyBook 3 do.

**Comment by JulianSatran** [comment]
I stand corrected (just reinstalled and checked). What about the Kybook 3 on the iPhone and the subscription? (I made it on the iPad but could not activate it on the iPhone)
