### ISSUE TITLE
Создание "подполок" для выбранной полки

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#11]
Создание книжных полок в виде дерева (или псевдо дерева): Часто требуется «подполка». Например, создали полку «Научные книги». А в нее «вложена», как узел дерева, 3 полки: «Гуманитарные»е «Естественно-научные», «Технические». Визуально они сделаны либо как узлы дерева, либо - просто чуть сдвинуты вправо для создания эффекта вложения в полку «Научные книги».

**Comment by kolyvan** [comment]
Я в целом противник древовидного интерфейса на мобильных устройствах. И применяю его только там где без него действительно никак. Как пример добавление SMB шары в KyBook. Хотя и там это вспомогательный элемент и можно просто вписать путь без хождения по дереву.

Подпапки в целом же выбиваются из дизайна. 

Я раcсматриваю KyBook как один из элементов доступа к книгам, при этом книги доступны по сети через opds каталог (calibre или tinyopds) , самбу и т.п. 
Возможность некоторой каталогизации через папки и сортировки, не делают KyBook полноценной библиотекой. Библиотека в моем понимании должна находится где то в сети (локальной или  интренете).

**Comment by DikBSD** [comment]
Все так... Но, к сожалению, в сетевых библиотеках очень примитивная организация книг. Можно ориентироваться только по Авторам/Жанрам, причем из-за ограничения схем Жанров книги часто "попадают" не туда, куда нужно (например, книги по самоличению - в раздел научных медицинских книг). И понимаешь, что книгу скачал не ту, не того направления, только тогда, когда скачал ее и открыл для чтения. Возможности ручной детализации и каталогизации в сетевых нет. Вот и хочется иметь такую возможность хотя бы в простеньких библиотекарях читалкок, чтобы можно было бы настроить каталогизацию книг "под себя". Ведь процесс чтения включает в себя не только открытие книги, но и нахождение ее. А удобная каталогизация как раз и способствует этому.
Вряд ли когда-нибудь сетевые библиотеки "дорастут" до этого..

Насчет вложенности подпапок и дизайна: Чтобы они не выбивались из дизайна можно сделать так, что внешние папки "скрывают" "свои" подпапки. При нажатии на них - появляется список этих подпапок.
