### ISSUE TITLE
Some characters not displayed properly on Kybook3 but displayed on Books (and other readers

### ISSUE THREAD

**Issue by JulianSatran** [kolyvan/kybook#110]
I did try different fonts - on all the quote signs on an ePub book are displayed badly on Kybook3. Perhaps I am missing a setting but I don't see what.

**Comment by JulianSatran** [comment]
Here is the text on iPhone Kybook3:

ON THE LAST morning of Virginiaâs bloodiest year since the Civil War, I built a fire and sat facing a window of darkness where at sunrise I knew I would find the sea. I was in my robe in lamplight, reviewing my officeâs annual statistics for car crashes, hangings, beatings, shootings, stabbings, when the telephone rudely rang at five-fifteen.
âDamn,â I muttered, for I was beginning to feel less charitable about answering Dr. Philip Mantâs phone. âAll right, all right.â
His weathered cottage was tucked behind a dune in a stark coastal Virginia subdivision called Sandbridge, between the U.S. Naval Amphibious Base and Back Bay National Wildlife Refuge. Mant was my deputy chief medical examiner for the Tidewater District, and sadly, his mother had died last week on Christmas Eve. Under ordinary circumstances, his returning to London to get family affairs in order would not have constituted an emergency for the Virginia medical examiner system. But his assistant forensic pathologist was already out on maternity leave, and recently, the morgue supervisor had quit.


And on Clearview on the desktop

ON THE LAST morning of Virginia’s bloodiest year since the Civil War, I built a fire and sat facing a window of darkness where at sunrise I knew I would find the sea. I was in my robe in lamplight, reviewing my office’s annual statistics for car crashes, hangings, beatings, shootings, stabbings, when the telephone rudely rang at five-fifteen.
“Damn,” I muttered, for I was beginning to feel less charitable about answering Dr. Philip Mant’s phone. “All right, all right.”
His weathered cottage was tucked behind a dune in a stark coastal Virginia subdivision called Sandbridge, between the U.S. Naval Amphibious Base and Back Bay National Wildlife Refuge. Mant was my deputy chief medical examiner for the Tidewater District, and sadly, his mother had died last week on Christmas Eve. Under ordinary circumstances, his returning to London to get family affairs in order would not have constituted an emergency for the Virginia medical examiner system. But his assistant forensic pathologist was already out on maternity leave, and recently, the morgue supervisor had quit.

**Comment by JulianSatran** [comment]
It  doesn't look exactly like it on the iPhone - the browser has its own layout for the fonts and I can't be sure how it will show on your screen - but on the Reader-View the should display the same text in the same language

**Comment by kolyvan** [comment]
Most likely this is some encoding issue with epub.
Unfortunately I can't say more without details (screenshots, sample epub file).

**Comment by JulianSatran** [comment]
I attach the epub.
The page that appears on the post - I took it with”copy” - from the KyBook screen.
If you want something else please let me know.

Regards,
Julo

**Comment by kolyvan** [comment]
No ebooks was provided

**Comment by JulianSatran** [comment]
I sent you one by email.want me to resend?

Regards,
Julo
