### ISSUE TITLE
iCloud never worked

### ISSUE THREAD

**Issue by whatthegit** [kolyvan/kybook#112]
Hi. Unlike KyBook 2, iCloud just never worked on Kybook 3. After adding iCloud, it is always empty but it isn’t really the case. Frankly, I’m so so disappointed with v3, as compare to v2. Please advise.

**Comment by kolyvan** [comment]
Hi, currently I don't know about any issues with iCloud in KyBook 3.
Could you please provide additional information about your issues with iCloud Drive and KyBook?
What you exactly mean by "_just never worked_"?

> disappointed with v3, as compare to v2.

You can continue use KyBook 2 if you wish. It's absolutely ok.
I plan to support KyBook 2 for at least this year.

**Comment by whatthegit** [comment]
Hi. Thanks for the response. Your feedback that there is no reported issue,
made me retry everything again. I realized that I need to create a “KyBook
3” folder in iCloud, which is why I had seen nothing in KyBook 3.

All is good now. Sidetrack a bit - I hope you can use iCloud to sync, as
the subscription is too high for a Pro user like me. Thanks for this great
app.
