### ISSUE TITLE
Добавление текста в закладки через страницу при перелистывании

### ISSUE THREAD

**Issue by evdenis** [kolyvan/kybook#113]
Настройки:
Page Turn : [Curl|Slide|No animation]

Действие:
Добавить в закладки текст (Mark), например, абзац, который выходит за границу страницы.

Проблема:
При таких настройках Page Turn, это невозможно сделать. Хочется, чтобы была такая возможность, как, например, это сделано в Marvin или в FBReader. В Marvin при подходе выделения к концу страницы, страница автоматом перелистывается на следующую с сохранением курсора выделения. В FBReader при подходе каретки выделения к границе страницы, происходит переключение в режим Scroll со сдвигом строк до необходимого количества.

**Comment by kolyvan** [comment]
Сожалею, но я не планирую добавлять запрошенную Вами возможность. Режим прокрутки позволяет делать заметки без ограничений.
