### ISSUE TITLE
Дефект: текст не всегда выделяется

### ISSUE THREAD

**Issue by vodnycheck** [kolyvan/kybook#114]
Устройство / ОС: iPhone 7 / iOS 12.1.2

Шаги по воспроизведению:
1. Открыть книгу
2. Долго нажать на каком-нибудь слове,  пока не появится выделение текста
3. Отпустить

Ожидаемый результат: слово остаётся выделенным

Фактический результат: выделение пропадает и невозможно скопировать слово в буфер обмена.

Примечание: баг воспроизводится примерно в 50% случаев. Не могу сказать точно когда и почему.

**Comment by kolyvan** [comment]
Простите, но я не могу повторить описанную Вами проблему. Сообщений о похожей ошибке от других пользователей у меня также нет.

**Comment by vodnycheck** [comment]
Нашел причину такого поведения.
Было поставлены галочки в: "Настройки" => "Во время чтения" => "Быстрая выборка" => "Всегда" и "Копировать"
Давно поставил эту настройку и забыл, не разобравшись как она работает и зачем, а теперь это вызвало у меня проблему.

**Comment by kolyvan** [comment]
> "Настройки" => "Во время чтения" => "Быстрая выборка" => "Всегда" и "Копировать"

Судя по этому Вы писали о KyBook 2 ??!
Пожалуйста, всегда указывайте версию KyBook если пишите не об актуальной версии!
