### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by pascalluo** [kolyvan/kybook#115]
Can add more Chinese fonts? The default one for Chinese is to thick ,not comfortable, can be thin as in iBook? Also the font setting for Chinese and English needed to be separated .

**Comment by kolyvan** [comment]
> Can add more Chinese fonts? 

You can always add any your loved font. It's pretty easy to do in KyBook.

> Also the font setting for Chinese and English needed to be separated 

You can use profiles to separate settings.

Please see the attached screenshots.

![kybook-add-font-1](https://user-images.githubusercontent.com/791320/51095514-1651bc00-1801-11e9-9645-acba2ececbf1.png)
![kybook-add-font-2](https://user-images.githubusercontent.com/791320/51095522-1ea9f700-1801-11e9-9d88-8ec87c1137c9.png)

![kybook-reader-profile-1](https://user-images.githubusercontent.com/791320/51095527-25386e80-1801-11e9-943a-977567bfdbe6.png)
![kybook-reader-profile-2](https://user-images.githubusercontent.com/791320/51095533-2c5f7c80-1801-11e9-9b9f-a9dba151032d.png)
