### ISSUE TITLE
Сбрасывается скорость воспроизведения аудиокниги при подключенных наушниках AirPods

### ISSUE THREAD

**Issue by wghot** [kolyvan/kybook#116]
Заметил такую проблему: если слушать аудиокнигу в наушниках AirPods, то скорость воспроизведения постоянно сбрасывается на значение по умолчанию (x1). Обычно происходит это после нажатия на кнопку «Pause/Play».
Версия 3 v0.7.1

В KyBook 2 с этим проблем нет, но есть другой небольшой баг. На экране блокировки телефона идет отображение времени до конца воспроизведения без учета скорости. То есть если стоит скорость x2, внутри показывается что до конца 30 минут, а на экране блокировки 60 минут и секунды идут быстрее.

**Comment by kolyvan** [comment]
Спасибо за сообщение о проблеме. Поправлю в следующем выпуске.

**Comment by kolyvan** [comment]
fixed in v0.7.3
