### ISSUE TITLE
Some characters not displayed properly on Kybook3 but displayed on Books (and other readers)

### ISSUE THREAD

**Issue by JulianSatran** [kolyvan/kybook#118]
The book - I sent it to Kolyvan email.
Here is link to the book available for 48 h

https://www.dropbox.com/s/fceekvhul6clv28/Patricia%20Cornwell%20FIVE%20SCARPETTA%20NOVELS%20-%20Patricia%20Cornwell.epub?dl=0

**Comment by kolyvan** [comment]
Even by your link this epub is displayed with invalid characters.
(See the attached screenshot.)
Just one more broken epub with wrong charset, nothing unusual. 

![screenshot-dropbox](https://user-images.githubusercontent.com/791320/52159709-e4db5a80-26f3-11e9-9d96-002f7e431a80.png)

**Comment by JulianSatran** [comment]
it displays well on Apple Books and other readers. Check it twice. Julo

**Comment by JulianSatran** [comment]
Refusing to fix an error will not earn you accolades!
Some of the characters that kybook3 does not display properly (all of them displayed by apple-books) are quotation marks and some other typographical signs. Besides apple-books other readers (including the calibre-viewer, pocketbook, clearview) display them OK.

**Comment by kolyvan** [comment]
> Refusing to fix an error 

There is no error. What else should I tell you?
Please stop posting messages without any useful information or error descriptions.

**Comment by JulianSatran** [comment]
As other readers display it well and the HTML is OK your renderer has an error.

**Comment by JulianSatran** [comment]
You don’t have to tell me anything. As for the useful information - there is definitely no new information in anything you don’t read!
The epub coding looks like valid and the charset is also correctly specified (8859-1). If you use the Google/Chrome renderer you encounter some error - but I am more inclined to point the finger to the google renderer that to epub editor as 4 different readers and  a epub editor display the text correctly.
As for your admonition to stop sending messages - I am within my rights as I paid for a working application (and that was my mistake!).

**Comment by kolyvan** [comment]
> You don’t have to tell me anything

It's no true. 
From my first reply - "_Just one more broken epub with wrong charset_".

You can easily verify my words.
- unzip the epub "Patricia Cornwell FIVE SCARPETTA NOVELS - Patricia Cornwell.epub"
- open any html file in OEBPS folder with any web-browser
- look at the result

Bellow the screenshot of the html file "CAUSEOFDEATH_full-body_3.html" opened in Chrome.

![ebook-in-chrome](https://user-images.githubusercontent.com/791320/52219899-516b7a80-28e9-11e9-8df9-1f96a145c639.png)

Every html file in this ebook has a wrong meta charset 'iso-8859-1'. 
But in fact every html file encoded in utf-8.
So the cause of visible artifacts like "â€œDamn,â€" is the wrong specified encoding.
The creator of this epub did a bad job.

So, I hope I completely explained to you this issue.

Please do not post anymore messages without any additional information.
