### ISSUE TITLE
Unable to use iCloud 

### ISSUE THREAD

**Issue by rravisankar** [kolyvan/kybook#119]
I am unable to use iCloud after deleting the KyBook 3 folder once. Pls help

**Comment by kolyvan** [comment]
> I am unable to use iCloud after deleting the KyBook 3 folder once

Seems legit. Sorry but what else did you expect?

> Pls help

Did you try recreate KyBook 3 folder anew?

Anyway it's not a bug.

**Comment by rravisankar** [comment]
Is there a way to force recreation of the folder from the app. KyBook2 works fine with the deletion.

Recreation manually does not have the iCloud~com format and hence it does not work

**Comment by rravisankar** [comment]
For someone else coming across this completely unhelpful thread,  here is how you fix the problem: 

Create the following folder structure on your mac and you should be set. 
They key is Documents folder under, the Kybook 3 (`iCloud~com~kolyvan~yar`) folder 
`/Users/<Your User ID>/Library/Mobile Documents/iCloud~com~kolyvan~yar/Documents/`

Time to use the app store ratings to reflect my satisfaction levels with the support :)
