### ISSUE TITLE
Изменение возможности выбора цвета для пометки/заметки

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#12]
Изменение возможности выбора цвета для пометки/заметки: сейчас сначала делается выделение предустановленным цветом, а уже потом, по тапу на этом выделении, появляется список цветов. Лучше, если бы было так: выделили слово/фразу, появился список действий, в котором есть элемент «цвет» (как сделано сейчас), но при нажатии на него появляется «подменю» - список цветов. Такой алгоритм требует меньше тапов.

**Comment by kolyvan** [comment]
Ну я вижу что в итоге тапов станет больше.
Но если добавить к выделению цветом еще и подчеркивание/зачеркивание, то с текущим меню нужно будет что  то делать, тут я не спорю.
