### ISSUE TITLE
No way to add online dictionary

### ISSUE THREAD

**Issue by krsuko** [kolyvan/kybook#121]
Hello, this is the best epub reader app i’ve found so far! however, in kybook 2 you have the ability to add your own online dictionary using the launch menu, why am I not able to do this in kybook 3? 
In kybook 3 you have the search feature which searches for the word on the internet on 4 different websites, why isn’t there an option to edit the websites so you can choose which ones you want? Adding the option to be able to add your own links would be so extremely useful, I really want to use kybook 3 because the interface looks better but without this feature I can’t use it

**Comment by kolyvan** [comment]
Sorry, but currently I do not plan to implement a feature like menu "Launch" in KyBook 3.

_A small explanation added._
Any customizable feature (when an user can alter the application behaviour) requires lots of work to carefully implement, test and support. When such feature is unpopular and rarely used (like Launch in KyBook 2) then it makes little sense to spend effort to implement. A lot of work for the developer, few users of the new function - no chance.

> own online dictionary

KyBook 3 supports offline dictionaries in format StarDict, dictd and Lingvo DSL. There are lots of freely available in the Internet.
