### ISSUE TITLE
No way to delete just one duplicate file

### ISSUE THREAD

**Issue by alexmadjar** [kolyvan/kybook#123]
If I have duplicates of the same file, it seems that deleting any one deletes them all (even across cloud folders!) this makes tidying up duplicates impossible.

**Comment by kolyvan** [comment]
Yes, when you delete a book, you also delete all associated files (book-files, summaries, etc). 
There is a detailed message about it in the Delete dialog.

**Comment by alexmadjar** [comment]
Yeah, I know. That's the problem. I'm saying that as a user I need a way to dedupe files. Not a "bug" so much as a feature request perhaps

**Comment by kolyvan** [comment]
For deletion of the file-duplicate, just open a book card, scroll down and swipe out the odd file.

**Comment by alexmadjar** [comment]
Oh okay! thanks! Didn't realize I could swipe that 😄
