### ISSUE TITLE
Feature Request: Select All for Notes on a book

### ISSUE THREAD

**Issue by alexmadjar** [kolyvan/kybook#127]
In Dashboard->Notes I'd love a way to select all the notes on a book at once.

**Comment by kolyvan** [comment]
You already can do that.
Open the book, go to notes screen, tap the Share button.

![kybook-notes-all](https://user-images.githubusercontent.com/791320/52467805-6e969680-2bd2-11e9-8489-d8aa6960e832.png)

**Comment by alexmadjar** [comment]
Ah! Sweet! Thanks man!
