### ISSUE TITLE
Сворачивающееся древовидное представление Оглавления

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#13]
Очень удобно сворачивающееся/раскрывающееся древовидное представление Оглавления. Все родительские элементы свернуты. Раскрыт только элемент, содержащий потомка-глава книги, которую читают в данный момент. При раскрытии другого узла дерева (Раздел книги) раскрытый ранее раздел сворачивается. Так намного удобнее ориентированться в Оглавлении, особенно, когда Оглавление содержит дерево с большим числом вложенных друг в друга Разделов/Глав/Подзаголовков - очень актуально для "серьезной" литературы. Не нужно долго пальцем пролистывать весь раскрытый список Оглавления. Достаточно просто раскрыть нужный Раздел - и все остальные - свергты.

**Comment by DikBSD** [comment]
Хороший пример такого дерева Оглавления - в читалке Djvu Reader.

**Comment by kolyvan** [comment]
Свое отношение к древовидному представлению я уже описал в #11 

Тут же замечу что действительно большие оглавление достаточно редкая штука.
Большинство книг в pdf,djvu вовсе не имеют никакого оглавления, оглавление в epub/fb2 часто просто небольшой список без под-элементов. Использование дерева для небольшого списка только замедлит доступ.
