### ISSUE TITLE
Миграция с Apple Books

### ISSUE THREAD

**Issue by ryazanec** [kolyvan/kybook#133]
Есть ли возможность перенести книги (много, порядка 3 000) из Apple Books в KyBook3 коллекциями (по авторам) ? Книги все скачаны с инета, закинуты в iPad с помощью iTools, который видит их россыпью. Коллекции создавались в iPad-e и книги переносил в них ручками. Спасибо.

**Comment by kolyvan** [comment]
Автоматически нет. Сторонние приложения не имеют доступа к книгами iBooks.
А так, тем же iTools, можете скопировать книги в папку KyBook/Documents/Books.
