### ISSUE TITLE
Kybook 3 

### ISSUE THREAD

**Issue by greghibbard** [kolyvan/kybook#134]
Annotation section is showing mark tags. Properly use the tags and do not show the tags.

**Comment by kolyvan** [comment]
Sorry, but I did not understand what you mean and what you suggest.

**Comment by greghibbard** [comment]
On the shelf, In the Book Card Metadata there is an annotation.  The annotation is displaying the data unformatted but it is actually HTML.  Just need to put an inline browser on that field.


Greg Hibbard

________________________________

**Comment by greghibbard** [comment]
I could clone from the repository and show you how and where to change the code if you need me to.

Thanks,

Greg Hibbard

Greg Hibbard

________________________________

**Comment by kolyvan** [comment]
Sorry, but the Annotation element is just plain text. It may not contain any HTML tags.
