### ISSUE TITLE
Feature request: Files app integration, Filter for file browser

### ISSUE THREAD

**Issue by ghost** [kolyvan/kybook#135]
1. It'd be good to have the app use the files app for browsing and opening documents. Like this [app](https://itunes.apple.com/app/pdf-viewer-read-review-annotate/id1120099014) Benefits: Caching of documents is managed by the files app, so that one does not have to re-download a file to use in another app.
  
2. It'd be good to have a filter option in the files browser, so that for example, one only see DJVU files. It seems that the app is already filtering out non-pdf or djvu files.

**Comment by kolyvan** [comment]
> It'd be good to have the app use the files app for browsing and opening documents. Like this app 

Sorry, but I do not want to completely redo the application design.

**Comment by ghost** [comment]
> Sorry, but I do not want to completely redo the application design.

Fair enough, but what about the second point?
