### ISSUE TITLE
Про версия и семейная подписаа

### ISSUE THREAD

**Issue by shadefff** [kolyvan/kybook#139]
Здравствуйте! Мой Apple ID привязан к семейной библиотеке, другой член семьи купил про версию, однако у на меня это не распространилось. При нажатии «восстановить покупки» ничего не происходит, просто значок загрузки. Можно ли с этим что-то поделать?

**Comment by kolyvan** [comment]
Прочтите пожалуйста информацию от Apple

https://support.apple.com/ru-ru/HT202023
https://support.apple.com/ru-ru/HT203046

**Comment by kolyvan** [comment]
Пожалуйста, не открывайте больше issues, не имеющие отношение к ошибкам или предложениям по улучшению приложения. Кроме того Ваш вопрос легко гуглится.
