### ISSUE TITLE
Возможно баг с содержанием

### ISSUE THREAD

**Issue by alexsda** [kolyvan/kybook#14]
При прочтении книги в горизонтальной ориентации выводим всплывающее окно с содержанием. Напротив каждой главы стоит номер страницы. Меняем ориентацию iPad. На странице книги автоматически произошел пересчет числа страниц, главы виртуально получили новые номера страниц, но на все еще открытом окне содержания эти же главы имеют прежние значения страниц. Назначение новых страниц главам не произошло. Повторное открытие окна содержания решает проблему, но это не логично.
Если сделать окно содержания модальным на весь экран, как в iBooks, то эта проблема уйдет, даже код править не надо будет. Плюсом получаем удобство прочтения длинных названий глав, которые обрезаются в текущем варианте исполнения, да и заметки удобнее читать. Можно продолжить под это окно красивую текстуру.

**Comment by kolyvan** [comment]
Я планирую в будущем совсем избавится от UIPopoverController для показа содержания.
Тогда и эта проблема будет решена.
