### ISSUE TITLE
Feature Request: Mark book as read

### ISSUE THREAD

**Issue by fjordBob** [kolyvan/kybook#140]
It would be cool if I had some kind of status for the individual books in my library. One possibility would be a kind of badge over the book which indicates whether it has already been read or not.

**Comment by kolyvan** [comment]
KyBook already has similar feature. It named _Tags_ .

![kybook-tags-2](https://user-images.githubusercontent.com/791320/53692621-f4c38880-3dde-11e9-82fe-1e02f1cebad1.png)
