### ISSUE TITLE
Логика работы с книгами на полке: чтение и возврат на полку.

### ISSUE THREAD

**Issue by alexsda** [kolyvan/kybook#15]
К примеру из большого списка полок мы нашли нужную, тачаем по ней и попадаем в нужную нам коллекцию. Находим какую-нибудь книгу и открываем ее. Далее по логике при необходимости взять другую книгу с этой полки надо вернуться назад, но этого не происходит. Приходится возвращаться в библиотеку, мотать список до нужной нам полки и, только потом, переходить на нее для выбора книги. А если надо просмотреть в поисках нужной на полк книг двадцать? Логичнее сделать кнопку ВОЗВРАТА на открытую полк.

**Comment by kolyvan** [comment]
Для кнопки возврата нету места на верхней панели.
Но наверно можно добавить поддержку новых жестов по краю экрана которые появились в семерке для возврата  на полку.

**Comment by kolyvan** [comment]
в 1.2.5 появилась возможность закрыть книгу и вернутся на книжную полку посредством длительного нажатия на кнопку доступа к боковому меню.
