### ISSUE TITLE
Баг при переносе книг на другую полку

### ISSUE THREAD

**Issue by alexsda** [kolyvan/kybook#16]
Если на полке находятся книга (одна или несколько), написанная несколькими авторами, то при перемещении любого количества книг с этой полки на другую выдается ошибка и, даже если на полке болше нет книг (как бы все переместились), при обновлении полки на ней остаются несколько книг. Такого не происходит при книгах, написанных одним автором

**Comment by kolyvan** [comment]
Спасибо, об этом баге уже известно.
Я планирую исправить его к выходу версии 1.3.0
