### ISSUE TITLE
Баг при переносе книг в режиме отображения ПАЧКИ

### ISSUE THREAD

**Issue by alexsda** [kolyvan/kybook#17]
Так же обнаружил, что в режиме отображения ПАЧКИ невозможно перемешать книги - при маркировке они просто открываются.

**Comment by kolyvan** [comment]
Перемещать можно сами пачки, но только через режим редактирования. 
Вызов меню по Long tap по ним пока не подключен.

Для книг же в верхней коллекции работает только тап для открытия книги, таков был первоначальный замысел. В планах есть добавить для верхнего экрана поддержку меню по long tap.
