### ISSUE TITLE
Увеличение размера картинок по двойному тапу

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#19]
Было бы очень удобно, если бы по двойному тапу на картинках, они могли увеличиваться на весь экран, как в iBooks.  Часто в книгах (fb2, epub) вставлены очень маленькие картинки, и для их рассмотрения как раз и нужно их увеличение (особенно это актуально для технической и компьютерной  литературы)

**Comment by kolyvan** [comment]
добавлено в v1.3.3

**Comment by DikBSD** [comment]
óÐÁÓÉÂÏ.
÷ÅÞÅÒÏÍ ÄÏÍÁ ÐÏÓÌÅ ÒÁÂÏÔÙ ÚÁÇÒÕÖÕ É ÐÏÔÅÓÔÉÒÕÀ...

ó Õ×ÁÖÅÎÉÅÍ,
÷ÁÄÉÍ

2013/10/22 Konstantin Boukreev notifications@github.com

**Comment by kolyvan** [comment]
```
óÐÁÓÉÂÏ. 
```

Наверно проблемы с кодировкой

**Comment by DikBSD** [comment]
Отправил сообщение с GMail напрямую - вот и проблема с кодировкой :-).
В том сообщении я выражал свою благодарность...
