### ISSUE TITLE
Report an issue action from kybook 3 app doesn’t work

### ISSUE THREAD

**Issue by mfilippov** [kolyvan/kybook#25]

**Comment by kolyvan** [comment]
Sorry, but the report is working good.

![kybook-report-issue](https://user-images.githubusercontent.com/791320/45479002-a535c580-b788-11e8-85a3-1c0ffdcb358e.png)

**Comment by mfilippov** [comment]
@kolyvan still not working for my. Maybe because I had alternative mail client?
