### ISSUE TITLE
Kybook2

### ISSUE THREAD

**Issue by ermolaevdn** [kolyvan/kybook#28]
Нет версии 1.2.4 kybook 2 в appstor
![e37a9af0-ac4f-44a9-aba9-20945046435b](https://user-images.githubusercontent.com/34489028/45563050-d24faa00-b854-11e8-9e55-76b804108cb2.jpeg)
![dbbefafc-8e49-44d7-af7b-6d25490f4f1f](https://user-images.githubusercontent.com/34489028/45563051-d24faa00-b854-11e8-8d6e-609f62251447.jpeg)

**Comment by kolyvan** [comment]
v1.2.4 доступна в AppStore
