### ISSUE TITLE
Sync between devices 

### ISSUE THREAD

**Issue by millyor** [kolyvan/kybook#31]
Hi I have been having problems  with syncing between devices the main reason i paid subscription to KyBook 3. this was also a problem on the older versions of KyBook I have downloaded the app to my devices ,paid  subscription . But no synchronise  I am very disappointed with this as I have already said it was a problem on other versions with only covers showing  and no content of book when opened  but at least it was a record of sorts  of what I had on my main device .can this be resolved

**Comment by kolyvan** [comment]
> have been having problems with syncing between devices

What kind of problem? 
Could you please give me more detail?
Did you read the help about the synchronization on the Synchronization screen?

> i paid subscription to KyBook 3.

There is a trial period 1 week, you can freely cancel your subscription without any payment.
There is also the full description about subscription terms on the In-App screen. 
Did you read it?
