### ISSUE TITLE
Kybook 2 tts issue

### ISSUE THREAD

**Issue by ghost** [kolyvan/kybook#32]
When doing tts on kybook 2, and changing the settings, the tts engine does not rewind to the start of the paragraph. In fact it skips to the next paragraph.

**Comment by kolyvan** [comment]
It's nor error nor issue. It's working as intended, it's the design decision.

**Comment by ghost** [comment]
It works differently on kybook 3 though. Where it rewinds properly.

**Comment by kolyvan** [comment]
Yes, because these are different applications and they have are different design and behaviour.

**Comment by ghost** [comment]
I feel that good design practice means that the behaviour should be the same across application versions.

**Comment by kolyvan** [comment]
No
