### ISSUE TITLE
Проблемы с аккаунтом

### ISSUE THREAD

**Issue by Sh00rF** [kolyvan/kybook#33]
Здравствуйте.
Подскажите, как узнать пароль на аккаунт? Вчера было скачено ваше приложение, а APP STORE и приобретён PRO пакет (15 сентября 2018 в 16:04), но без регистрации аккаунта, мне автоматически привязали логин без email’a и пароля, а теперь, чтоб изменить имел мне нужен пароль. Как можно получить пароль или код активации для аккаунта ?
Логин: DGrV7lmjM
Вышлите подробную инструкцию или решение данного вопроса на электронную почту.
Shoorf.od@gmail.com
За ранее спасибо.

**Comment by kolyvan** [comment]
К сожалению смена/добавление пароля через приложение пока не реализовано. 
Как вы понимаете вручную менять/назначать/разглашать пароли по сообщению я не могу.
Подождите немного, необходимая функциональность  будет реализована в следующем выпуске.
Прощу прощения за неудобство.
