### ISSUE TITLE
Apostrophes

### ISSUE THREAD

**Issue by Mondyboy** [kolyvan/kybook#34]
I’ve noticed that apostrophes are left hanging at the end of a line.  So for example for boyfriend’s, the line ends with the apostrophe and the new line begins with an s and then onto the next word.

**Comment by karlic** [comment]
I have this problem too. 

"... reports of the previous night's event ..." breaks at the apostrophe and the s appears on the next line.

" ... must have known he'd caused ..." also breaks at the apostrophe.

**Comment by kolyvan** [comment]
fixed in v0.5.3 (91 build)
