### ISSUE TITLE
Случайно купил подписку на год

### ISSUE THREAD

**Issue by ghost** [kolyvan/kybook#35]
Здравствуйте! Я случайно купил подписку на год, а хотел купить про с kybook2. Можно ли как-то вернуть деньги ? Kovall89@gmail.com моя Почта

**Comment by kolyvan** [comment]
На экране встроенных покупок есть кнопка Управление подпиской, нажмите.
И да в течении первой недели деньги за подписку не списываются. Просто перейдите по кнопке и отмените подписку.

**Comment by ghost** [comment]
Прошу прощения, но у меня сразу списались деньги - 949руб. Подписку я отменил, но она закончится 17.09.2019г

**Comment by kolyvan** [comment]
Странно, Apple вроде не должна сразу списывать деньги за подписку.
Я всегда считал что дается неделя на проверку подписки перед платежом.

**Comment by ghost** [comment]
Ну да, сразу сняли(( 
То есть никак не получится назад вернуть, да?)

**Comment by kolyvan** [comment]
К сожалению я не знаю, платежами занимается Apple, по всем вопросам оплаты, возвратов и т.п. решают только они.

**Comment by kolyvan** [comment]
Напиши в поддержку Apple, скажите что купили подписку по ошибке, попросите вернуть деньги. Они достаточно лояльны к пользователям.

**Comment by ghost** [comment]
Понял) спасибо

**Comment by ghost** [comment]
Все получилось! Спасибо
