### ISSUE TITLE
Kybook3 on MacBook

### ISSUE THREAD

**Issue by gkpalden** [kolyvan/kybook#386]
Hi,
I tried to install Kybook3, which I love very much, on my MacBook but it crashes all the time.
Could you please help me with this?

**Comment by benjaminv** [comment]
Mine crashes once click to open any book, Kybook 3, paid version, Monterey on MBA M1. Browsing to the folders is fine though. Seems no fix at the moment. Apple does not garantee the use of iOS apps on macOS.

**Comment by gkpalden** [comment]
That's the problem I experience, same Monterey on MBA M1. It's a shame, because Kybook is so much better then iBooks, would be wonderful to use it on Mac too.

**Comment by gkpalden** [comment]
Found that one quite good: https://www.yomu-reader.com/
Also available on Mac.

**Comment by gkpalden** [comment]
Closed
