### ISSUE TITLE
Use Keywords in PDF as Subject in KyBook

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#39]
I'm sorry to bring this up again, but I have 250 EPUBs/mobis in KyBook nicely sorted by subject and then 350 PDFs just randomly added at the bottom and this is my only complaint about KyBook.

Following on from your comments in https://github.com/kolyvan/kybook-reader.com/issues/2, I have had another look at this.

Calibre *does* add its 'tags' to 'Keywords' (comma separated) in a PDF when you do 'Save to disc in a single directory'. So, it seems the Keywords in a PDF could be used as the subject(s) for PDFs in KyBook.

Calibre's tags already get written as 'Subject' to EPUBs and are successfully used as subjects(s) for EPUBs in KyBook.

Thanks.

**Comment by kolyvan** [comment]
Calibre `Tags` is not standard method to store Tags/Subject info and not used by anyone except as Calibre. In fact the same Calibre  is not the best or most popular ebooks catalog software. 
Sorry, but that is why, I can't spend time to support some non-standard method from some non-major software to handle metadata in PDFs.

**Comment by kolyvan** [comment]
Oh, I thought about this issue with subjects, tags in PDFs and Calibre.
Ok, You have convinced me. 
I will look into this issue and try to implement the support of `Calibre Tags` in the next beta release.

**Comment by kolyvan** [comment]
In beta build 93 v0.5.4 I added handling of Calibre Content Server Tags/Series passed as text in Summary. 
Attention -  It works only when you download a book from Calibre OPDS Catalog Server.
Calibre does not modify the file itself, it only passed Tags/Series info in OPDS Entry Summary field.
And when KyBook downloads a book from Calibre Server, the Tags/Series information could be handled and added into the ebook metadata.
So, for appearing Tags/Series info, all books must be deleted and redownloaded from Calibre Server.

**Comment by karlic** [comment]
Is there any way to download **_all_** files from Calibre OPDS Catalog Server? I have over 300 pdfs. :-(

Alternatively, if I select all files and `Save to disc in a single directory` in Calibre the `Tags` get written to `Keywords` in PDFs. Could KyBook not pick these up and put them into `Subjects` when the files are dropped on to `File sharing` in iTunes?

**Comment by kolyvan** [comment]
> Is there any way to download all files from Calibre OPDS Catalog Server

All books at once no.
There is no such thing like `list of all ebooks in OPDS Catalog`.

In 96 buld, I added the ability to batch download books on the page from OPDS Catalog.
Perhaps this feature will help.

![opds-batch-download_1](https://user-images.githubusercontent.com/791320/46083423-c6fd6680-c1e4-11e8-900b-857f491c9595.png)
![opds-batch-download_2](https://user-images.githubusercontent.com/791320/46083430-ca90ed80-c1e4-11e8-8515-953b2f71fa01.png)

**Comment by karlic** [comment]
This is FANTASTIC! You are a star. I can download **_all_** books by batch downloading from the `By Newest` OPDS view.

Moreover, PDFs and DjVus get their subjects too.

Thank you, thank you, thank you. :-D

P.S. This is a real selling point for KyBooks as I think a lot of English-speaking people use Calibre.
