### ISSUE TITLE
Скорость перелистывания страниц

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#4]
Увеличение скорости перелистывания страниц. Сейчас перелистывание очень медленное.

**Comment by kolyvan** [comment]
Я пока не знаю способа решения данной проблемы. 
За скорость анимации в данном случае отвечает система.
Частичное решение, добавить собственную анимацию смены страниц (подобно слайдингу в Айчиталке)
Решение упирается в тот же самый участок кода как и в #2
