### ISSUE TITLE
BUG: Deleting a book doesn't delete entries in Authors or Subjects (and others?) in Cataloguer

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#40]
KyBook 3 v0.5.4 | #94

1. Delete KyBook 3 and install the above version. 
2. Delete the three books that are installed by default.
3. Close KyBook 3 and re-open
4. Go to `Library -> Cataloguer -> Authors`
5. The authors are still listed
6. Go to `Library -> Cataloguer -> Subjects`
7. The subjects are still listed

I have **not** verified it, but I suspect any `Tags`, `Ratings`, etc. could also be left 'orphaned'.

**Comment by kolyvan** [comment]
Yes, it's working as intended.
User may add Author/Seria/Subject/Etc manually and KyBook can automatically extract a category from e-book metadata.
Unfortunately KyBook can't discern between these two scenario.
So KyBook can't delete empty categories but an user can.
There is a special menu `Delete empty` for that.

![kybook-delete-empty](https://user-images.githubusercontent.com/791320/45936571-96a6a400-bffb-11e8-853d-d80f7e93b207.png)

**Comment by karlic** [comment]
Ah, I assumed you were doing a `select` for `sid` in `books_subjects` and `delete` from `subjects` if there were no results, but there was a bug in the code. :-) 

I've addd a FAQ to explain the behaviour and apologise for assuming you wrote buggy code ;-)

**Comment by kolyvan** [comment]
> I assumed you were doing a select for sid in books_subjects and delete from subjects if there were no results

Yes, you are right. I use `DELETE FROM subjects WHERE sid NOT IN (SELECT sid FROM books_subjects);` for cleaning empty subjects.

> but there was a bug in the code

Excuse me, but I do not know about any bug related to cleaning empty categories feature at this moment.

> apologise for assuming you wrote buggy code

Um, sorry, what you talking about?
The quality of the code in KyBook are quite typical, contains some bugs not more not less as any other app.

**Comment by karlic** [comment]
> Yes, you are right. I use DELETE FROM subjects WHERE sid NOT IN (SELECT sid FROM books_subjects); for cleaning empty subjects.

I thought you were calling this when the _**book**_ was deleted and therefore a bug.

> Excuse me, but I do not know about any bug related to cleaning empty categories feature at this moment.

You are correct, there is no bug in the 'delete empty' feature.

> Um, sorry, what you talking about?
The quality of the code in KyBook are quite typical, contains some bugs not more not less as any other app.

I was making a joke. Most programmers do not admit to bugs and blame other programmers. :-)
