### ISSUE TITLE
BUG: Misc info in Book card has wrong label

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#41]
KyBook 3 v0.5.4 | #94

1. Go to Cataloguer -> New
2. Tap a book card
3. Scroll down to Misc info and tap
4. The label 'File Name' appears for the file's name **and** its size

**Comment by kolyvan** [comment]
Yes, I know. Still have no time to fix it.

**Comment by kolyvan** [comment]
Fixed in 95 build
