### ISSUE TITLE
COSMETIC: Order of card sizes in bookshelf layout

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#42]
KyBook 3 v0.5.4 | #94

It would be more logical to have the menu read

```
Covers
Mini cards
Normal cards
Large cards
```

so that the size of the card increases as the user moves down the menu.

It might also make sense to rename 'Cards' to 'Normal cards'

**Comment by kolyvan** [comment]
Maybe yes, but it's too minor change.
Now menu items are ordered in the `most preferable` and changing to `most logical` will not made KyBook more user friendly.
