### ISSUE TITLE
FR: Add ability to limit book searches to title/author

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#43]
In the book search dialogue box, it would be **nice** to be able to limit the search to the title or author, etc.

Something like:
`title: Harry Potter`
or
`author: Rowling`

**Comment by kolyvan** [comment]
In fact something like this KyBook  already can do.

On the search screen there is a settings where you can limit scope of searching.

And in a catalog search you can use 'intitle:', 'inauthor:' prefixes, but this works only when a OPDS catalog supports a search scopes.

![kybook-search-settings](https://user-images.githubusercontent.com/791320/45936917-010d1380-bfff-11e8-97a5-58e0c22050f5.png)
![kybook-catalog-search](https://user-images.githubusercontent.com/791320/45936921-04080400-bfff-11e8-8f1f-c4ed79e10080.png)
