### ISSUE TITLE
COSMETIC: 'Edit tags' in book card view is non-standard

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#44]
KyBook 3 v0.5.4 | #94

1. Tap a book
2. Tap 'Edit' in the book card
3. '**_Edit_** tags' should read '**_Add a_** tag' to match the format of '**_Add a_** title', '**_Add a_** series', etc.

**Comment by kolyvan** [comment]
It has sense since you can not only `Add a tag` but also delete or create new.

**Comment by karlic** [comment]
I thought that too, but you can also create a new subject in `Add a subject`, etc. Although, I agree the method of creation is different and tags have an icon and colour.

BUT, you can't actually **_edit_** an existing tag in that dialogue (change its colour or icon).
