### ISSUE TITLE
COSMETIC: Format of Metrics in book card could be improved

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#45]
KyBook 3 v0.5.4 | #94

1. Tap a book
2. Tap Read
3. Scroll through the book
4. Close the book
5. Tap the book
6. Scroll down to 'Metrics' in the book card
7. It reads 'Read 33% in 7 secs, 6 pages'

For native English speakers, this would read better as:
`Read 6 pages (33%) in 7 secs`
or, possibly
`Read 33% (6 pages ) in 7 secs`

**Comment by kolyvan** [comment]
Yes, there is definitely some confusion about this metrics.
 'Read 33% in 7 secs, 6 pages' - means what a book has 6 pages total and an user finished read 2 pages in 7 seconds.

**Comment by karlic** [comment]
OK, so that would read better as:
'Read 33% of 6 pages in 7 secs'
or:
'Read 2 of 6 pages (33%) in 7 secs'

Either way, I think the pages and percent need to be next to each other and not separated by the time.

**Comment by kolyvan** [comment]
Fixed in 95 build (v0.5.5)
