### ISSUE TITLE
COSMETIC: style of hints/comments in Add OPDS Catalog view could be improved

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#46]
KyBook 3 v 0.5.4 | #94

Tap `Add`
Tap `OPDS Catalog`

The comments under the `LIST OF KNOWN OPDS CATALOGS` seem to be coloured red or black in a random fashion. It would make sense to have:

- good links in green
- so-so ones in black
- bad/broken ones in red.

Additionally:

- `O'Reilly Media Catalog` should read, 'Paid content only. No search' ('r' missing from 'search')
- `........ (Lib)` should read, 'Unreachable for the casual user'
- `........ (Tor)` should read, 'Reachable via the TOR network'
- `e-reading.club` should read, 'Requires authorization'
- `OpenEdition` should read, 'No search. No downloads'
- ``Izzy`s freie Bibliothek`` should have ' not ` in Izzys (apostrophe, not back tick)

**Comment by kolyvan** [comment]
> It would make sense to have:

Unfortunately, there are themes, and just to set green/red color is not working except default Day theme.

> O'Reilly Media Catalog should read, 'Paid content only. No search' ('r' missing from 'search')

These remarks were used in testing issue mostly.
Most likely I will remove them completely later. 
They have no sense for casual user.

**Comment by karlic** [comment]
Actually, I thought those remarks were quite useful. At least I know _**before**_ connecting that I will have to pay or the downloads might be broken. Users will feel cheated if you have OPDS links that then don't work when they connect.
