### ISSUE TITLE
iOS 16

### ISSUE THREAD

**Issue by gkpalden** [kolyvan/kybook#465]
Hello,

will KyBook 3 work on iOS 16?

I’d like to know that, *before* installing iOS 16, otherwise I’ll stick with iOS 15.

An answer is highly appreciated!

Palden.

**Comment by korostylov** [comment]
Reader rotates with phone. Blocking doesn’t work (((

**Comment by gkpalden** [comment]
Tried an tested on iOS 16, seems all ok, just a notice that the sync doesn't work ... but it does ;-)

**Comment by gkpalden** [comment]
Found that reader quite good, also available on MacBook: https://www.yomu-reader.com/
