### ISSUE TITLE
Режим конспект

### ISSUE THREAD

**Issue by ghost** [kolyvan/kybook#48]
Скажите, а в 3 версии нет функции автоматического добавления текста в конспект? Во второй версии можно было нажать копировать и автоматически этот текст попадал в конспект

**Comment by kolyvan** [comment]
Мне кажется этот вопрос можно было задать на форуме. Он же никакого отношения к `issues` не имеет.

Касательно ответа на вопрос - нет, в KyBook 3 такой функции нет.
