### ISSUE TITLE
No select or select all options in context menu for cataloguer

### ISSUE THREAD

**Issue by nlivni** [kolyvan/kybook#49]
Appears in context menu for for file tree and downloads but not in cataloguer

**Comment by kolyvan** [comment]
Yes, you are right.
There is no much sense to have `Select All` in the Cataloguer.

**Comment by nlivni** [comment]
You're right. I didn't mean in the Cataloguer, but rather its subsections like, New and Read. I'll resubmit.

**Comment by kolyvan** [comment]
Ok, I will look what I can do with SelectAll in Cataloguer subsections. Maybe in next beta release.

**Comment by nlivni** [comment]
That would be awesome. It is currently available in some subsections but not in others. In KyBook2 I know I could sort by subject and be able to batch assign categories to books missing a subject.

This is very helpful. Thank you for the fast response and for reopening the issue.

**Comment by kolyvan** [comment]
Implemented in the beta build 97.
