### ISSUE TITLE
Пометка цветом места текущего чтения (главы) в списке Оглавления

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#5]
При переходе в меню Оглавления книги было бы очень удобно, если бы текущая читаемая глава как-то выделялась цветом в списке Оглавления и позиционировалась вверх - удобно видеть, где находишься.

**Comment by kolyvan** [comment]
Попробую добавить уже в 1.2.1

**Comment by kolyvan** [comment]
добавлено в 1.2.2
