### ISSUE TITLE
No Select or Select all in New or Read sections of Cataloguer

### ISSUE THREAD

**Issue by nlivni** [kolyvan/kybook#51]
I want to tag New or Read books. These are exactly the contexts in which I want to do batch editing so I'm surprised that I can't select more than one book.

I do find Select in the Subjects view, which is good because I can reassign Subjects. Can it be added to the other subsections of Cataloguer?

**Comment by karlic** [comment]
I think you can do this in the Library view.

1. Sort the books `by Date` or `by Progress` (top-right of screen)
2. Tap and hold any book
3. Tap `More` on the pop-up menu
4. `Select` or `Select All` the books you wish to edit
5. Tap `Edit` at the bottom-left of the screen
6. Do the edits you wish

**Comment by nlivni** [comment]
this thread can be merged with 49 or closed. I am not sure what a library view is in KyBook 3. I am wanting to sort by subject and assign a new subject to those missing one, ensuring all have subjects. This is a kybook2 feature missing from kybook3.
