### ISSUE TITLE
FR: Please add two-page spread to landscape for PDFs

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#54]
I know you have said that text in two-page spreads for PDFs is too small to be useful and this may be true (although I don't entirely agree), but I can think of at least 3 use cases for a two-page landscape view:

1. A map, diagram, or picture over a two-page spread
2. Text on the verso refers to a graphic on the recto (bird, plant, etc. reference books)
3. A flow chart flows back and forth across the two pages

Personally, I use 2. a lot. Even if it is not a commonly requested feature, it is attention to this kind of detail for people who **_do_** use it that is likely to make them recommend KyBook to others.

**Comment by kolyvan** [comment]
I may only repeat my opinions:
- PDF pages commonly just does not fit on the mobile devices screens.
- Double-pages absolutely does not fit.
- Users constantly must use zoom to read one PDF page.
- Zooming and reading are unfriendly for an user.
- Zooming  and reading of double-pages are unfriendly even more.
- So double-pages (page-spread) for PDF/DJVU is not useful mode.
- It's just 'wow feature' but not for the real life usable.

**Comment by karlic** [comment]
Maybe let the user decide? I used it all the time when my PDFs were in GoodReader (on an iPad mini). For me its a 'must-have' feature , otherwise I have to keep sending to GoodReader. For me, KyBook's main selling point is 'all books in a single app'.

![photo 30-09-2018 11 24 08](https://user-images.githubusercontent.com/6543702/46257015-b120c780-c4aa-11e8-9cbb-8219cb955c3b.png)
![photo 30-09-2018 11 19 55](https://user-images.githubusercontent.com/6543702/46257016-b120c780-c4aa-11e8-8690-ceaa4ca28ada.png)
![photo 30-09-2018 10 38 53](https://user-images.githubusercontent.com/6543702/46257017-b1b95e00-c4aa-11e8-8339-bec99bc097cc.png)

**Comment by GitHub-tlinn** [comment]
I'm not sure why you are removing a feature that was previously available to users but it is a regrettable decision on your part. Karlic presented three different use cases that are perfect examples of why it is important to have this option. Maybe you're imagining this feature on an iPhone but I use it ALL THE TIME on my iPad Pro. Its removal is the reason I will not be committing to Kybook 3. I hope you reconsider.

**Comment by toledobastos** [comment]
Another one here asking for this. Yes, it's a very niche feature but definitely good to have.
