### ISSUE TITLE
FR: Show 'Nulls' in (some) Cataloguer categories

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#55]
In `Cataloguer` -> `Subjects`, books that do not have a subject do not appear. However, it would be useful to have them listed as, 'Undesignated', especially when the user wants to find 'Nulls' and give them a subject.

This may also apply to `With rating`, `Series`, `Authors`, and `Publishers`.

**Comment by karlic** [comment]
On second thoughts, maybe 'Undesignated' should be 'Unassigned'. You might then want to consider renaming the 'Exclude' menu item (in book card and Cataloguer categories views) to 'Unassign'

**Comment by kolyvan** [comment]
Thank for suggestion, I will think about it.

**Comment by karlic** [comment]
Just a reminder that the name will have to be consistent with your decisions on https://github.com/kolyvan/kybook/issues/61 (maybe 'unshelved' would be apt)

**Comment by kolyvan** [comment]
Not appropriate for the current design.

Also, the similar functionality may be achieved  already now by selecting proper order in `All books` bookshelf. For example to see all books without subjects, just open `All books` bookshelf, select sort order `by Subject`. Books without subjects will be placed at the bottom of screen in the separate unnamed section.
