### ISSUE TITLE
FR: Add a 'Filetype' category to Cataloguer

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#56]
To differentiate PDFs, EPUBS, etc.

**Comment by karlic** [comment]
Second thoughts on this one too. 

In `Book card` -> `Misc info`, the filetype is 'E-book format', so you'd need to standardise.

Because Cataloguer categories are single words (more or less), I'd opt for:
'Filetype' in Cataloguer and 'E-book filetype' in `Book card` -> `Misc info`
**_or_**
'Format' in Cataloguer and 'E-book format' in `Book card` -> `Misc info`

(I guess you could drop the word 'E-book' from `Book card` -> `Misc info` in either case. What does bookcard.miscinfo.ebookformat say for an audio file? Because 'E-book' doesn't really make sense for that anyway.)

**Comment by kolyvan** [comment]
Sorry, I have no opinion about this yet.
A bit later.

**Comment by kolyvan** [comment]
Added new sort order 'by Format' in the beta v0.6.3.
