### ISSUE TITLE
FR: Alphabet in Library?

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#58]
When you have a large number of books in the Library (or other bookshelves), it takes many swipes to scroll down to where you want to be.

Maybe it would be useful to have the letters of the alphabet [A-Z#] running down one side so the user can 'skip' to a particular location.

Apple's Contacts app has this, but I think I have seen it done better in another app, where the alphabet would only appeared when the user started scrolling.

**Comment by kolyvan** [comment]
Sorry, but I am unsure what `an index list on the right side` could be suitable for the current design of the KyBook bookshelves. 
And there is a chance what adding similar list into Bookshelf is impossible due to some technical limitation .

I will check but I can't promise.

**Comment by kolyvan** [comment]
Not appropriate for the current design
