### ISSUE TITLE
BUG: PDF horizontal scroll lock doesn’t survive device rotation

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#59]
KyBook 3 v0.5.5 | #98

0. (`Curl` page turn mode is set)
1. Tap a PDF book
2. Tap `Read`
3. Tap `Preferences` and set `Fit Mode` to `Whole page`
4. Turn device to portrait
5. Pinch and zoom so text fits page
6. Two-finger tap middle of page
7. Check horiz. scroll lock is set
8. Rotate device to landscape and back to portrait
9. Horiz. scroll lock is lost

**Comment by kolyvan** [comment]
It's not a bug but an implementation details (or limitation).

By my current opinion, after rotation, a former horizontal lock is anyway unusable and must void.

**Comment by karlic** [comment]
> ... (or limitation)

It's quite a severe limitation when I'm trying to read scanned novels. Every time I move the device enough to rotate the screen, I lose the horizontal scroll lock.

Locking rotation at the device level seems to solve (work round) the problem. Maybe a lock rotation at the app level (I think you added this to iPhone) either manually or automatically when horizontal scroll lock is activated would help.
