### ISSUE TITLE
Подчеркивание слов/фраз в тексте

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#6]
Подчеркивание фраз (слов) при чтении книги (как в iBooks) линиями различной формы(волна, прямая, двойная и т.д.) и цвета. Очень часто более предпочтительно подчеркнуть фразу, а не пометить ее цветной полоской.

**Comment by kolyvan** [comment]
Это возможно хотя и потребуется внести достаточно много изменений в коде.
