### ISSUE TITLE
BUG: Delete menu item missing

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#64]
KyBook 3 v0.5.6 | #99

1. Cataloguer -> Subjects
2. Long tap a subject
3. Tap delete
4. Tap delete on the confirmation dialogue
5. Subject and books are deleted as expected
6. Tap Cataloguer -> Subjects 
7. Long tap a subject. There is no Delete menu item (only Exclude | Collections | Rename)

I tried closing KyBook and restarting, but the problem persists.

I have deleted other subjects and books before, so don't know why this should happen now.

**Comment by karlic** [comment]
OK, maybe I'm going senile. I've just deleted KyBook 3 and re-installed and the menu item has NOT come back. Was it ever there? I'm sure it was when I was looking at the localisation strings.

**Comment by karlic** [comment]
Just checked on my partner's iPad and Delete should definitely be on the menu. Tried switching to `Advanced interface`. Still not there. Has KyBook remembered a faulty menu after a re-install?

**Comment by kolyvan** [comment]
Maybe you trying to delete empty subject?
If yes, then is not a bug. You can only `Exclude` empty subject.

**Comment by karlic** [comment]
> Maybe you trying to delete empty subject?

No, I had reinstalled so I had the default books and was trying to delete the subject 'Fiction' (which had books in it).

Anyway, I deleted KyBook 3 again and, this time, deleted TestFlight and installed KyBook 3 from the App Store. Went to Cataloguer -> Subjects, long-tapped Fiction and the Delete menu item was there.

One thing I noticed was that even after deleting KyBook 3 and TestFlight, after reinstalling KyBook 3 it had remembered how I had arranged the iPad and Cataloguer icons and remembered that I had a connection to Dropbox. **_Where are those settings stored?_**

**Comment by karlic** [comment]
Deleted KyBook 3 again. Reinstalled TestFlight. Installed KyBook 3 from TestFlight. There is no Delete menu in Cataloguer -> Subjects. So this is a bug in KyBook 3 v0.5.6 | #99 or TestFlight.

**Comment by kolyvan** [comment]
It's not a bug. 
From 99 build, KyBook does not show anymore `Delete` menu item for empty categories.

**Comment by kolyvan** [comment]
> Where are those settings stored?

In the user's defaults. 
Technically, in Library/Preferences/com.kolyvan.yar.plist file in the application container.
Also part of them synced via cloud.

**Comment by karlic** [comment]
Category is **_NOT_** empty
Two videos showing:
V0.5.5 | #98 **_with_** Delete menu (installed from App Store with TestFlight uninstalled)
V0.5.6 | #99 **_without_** Delete menu (installed from TestFlight)

https://www.dropbox.com/s/90jdgbf9eeco39p/V0.5.5-98.mp4?dl=0
https://www.dropbox.com/s/y1wx7tothehypvc/V0.5.6-99.mp4?dl=0

**Comment by karlic** [comment]
So, I've had a poke about for the plist files for KyBook 3 and it looks like the menu items get written out to a plist file. Is it possible they're not being written out (or read back in) properly?

**Comment by kolyvan** [comment]
> Category is NOT empty

Ah, Thank you very much for this detailed presentation.
Now I saw the issue.

To temporary fix, just change the layout to `Cards` from `Covers`.
In the `Covers` mode KyBook does not count the books on the subsheves and always assumes what a bookshelf is empty. 

I will fix it the next beta version.

**Comment by kolyvan** [comment]
> So, I've had a poke about for the plist files for KyBook 3 and it looks like the menu items get written out to a plist file

KyBook stores a list of recent used menu items in the user-defaults plist.
And uses this list only for sorting menu items only when full list of menu items are too big ( > 3).

**Comment by karlic** [comment]
I believe this is now resolved.
