### ISSUE TITLE
Изменение размера кнопок панели инструментов и расстояния их друг от друга

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#7]
Желательно увеличить размер кнопок панели инструментов в режиме чтения книги и отодвинуть их друг от друга.  Часто палец задевает соседние кнопки....

**Comment by kolyvan** [comment]
Хм, на iphone менятmся точно ничего не будет, места там и так маловато.
На iPad же размеры наверно можно несколько увеличить.
Хочу заметить что это будет уже второе увеличение размеров у элементов интерфейса на iPad.
