### ISSUE TITLE
Время работы экрана по умолчанию

### ISSUE THREAD

**Issue by pianofox** [kolyvan/kybook#71]
Здравствуйте!  Огромное спасибо за ваш труд и чудесное приложение,  которое заменило мне все остальные аналоги. Единственный нюанс о котором я бы хотел уточнить это возможность оставлять экран включенным во время чтения книги. Можно ли сделать так, чтобы экран не гас после 30 секунд по умолчанию телефона, при этом не меняя общие настройки телефона из вне? Мне удобнее читать с небольшим шрифтом, но при этом не успеваю дочитать страницу и экран гаснет и блокируется по умолчанию, что иногда доставляет неудобство. Можно ли это как-то исправить? Спасибо большое!

**Comment by kolyvan** [comment]
Посмотрите в настройках приложения - Управление/Читалка -> Отключить таймер простоя.

![kybook-reader-idle-timer](https://user-images.githubusercontent.com/791320/46710861-35363480-cc8d-11e8-970c-f0858e370187.png)

**Comment by pianofox** [comment]
Вот это да!  Спасибо большое! Честно говоря даже и не подозревал о столь обширном меню настроек на главном экране приложения и раньше искал эту опцию в меню настроек при открытой книге. Большое вам спасибо за такую громадную работу!
