### ISSUE TITLE
Doesn’t support multiple OPDS libraries n one machine.

### ISSUE THREAD

**Issue by CovertDad** [kolyvan/kybook#72]
I have both Calibre and Mylar running on the same machine on my network.  KyBook 2 lets me add calibre, but when I try to add Mylar, I get a message stating the library already exists for the address (the ip on my local network).  If the library key was the full URL rather than just the host, this wouldn’t be an issue.

**Comment by kolyvan** [comment]
Sorry, but I do not plan to change anything in KyBook 2 except fixing critical bugs.
