### ISSUE TITLE
KyBook 3 crashes when opening .epub file with 940 pages at 84 MB

### ISSUE THREAD

**Issue by MortenZdk** [kolyvan/kybook#73]
I got a .epub file with 940 pages at 84 MB that makes the KyBook 3 crash on a new iPad running latest iOS (12.0.1).

The file can be read in other apps, e.g. the Readdle Documents 6.7.

How to debug this problem ?

Btw, thanks for a great eBook reader :-)

**Comment by kolyvan** [comment]
> How to debug this problem ?

Send me a link to the epub if you can,  please.

**Comment by MortenZdk** [comment]
It is not a public available file, so I have just send it through WeTransfer to your e-mail.

Let me know if you need further information.

**Comment by kolyvan** [comment]
Thank you very much for the sharing epub.
I received the epub and could reproduce the crash.

**Comment by MortenZdk** [comment]
Good to hear, and thanks for looking into this.

I just evaluated several eBook reader for iOS, and KyBook 3 was the best I think, so I really appreciate your work.

**Comment by kolyvan** [comment]
Fixed in v0.5.6

**Comment by MortenZdk** [comment]
Thanks, I can confirm that.
