### ISSUE TITLE
KyBook 3 Scrolling Bar

### ISSUE THREAD

**Issue by weiweihuanghuang** [kolyvan/kybook#74]
Kybook2 has a very useful scrolling bar at the bottom is that gone now?

**Comment by kolyvan** [comment]
KyBook 3 has the page slider too.
Just tap on the page counter on the bottom bar.

![kybook-slider](https://user-images.githubusercontent.com/791320/46779076-b9ee8480-cd59-11e8-9d8c-388fa7bcc707.png)
