### ISSUE TITLE
Feature Suggestion: Bookmark preview

### ISSUE THREAD

**Issue by weiweihuanghuang** [kolyvan/kybook#75]
Would be useful if the first few lines of a bookmark could be previewed in the bookmark overview

**Comment by kolyvan** [comment]
Already has.

![kybook-bookmark-1](https://user-images.githubusercontent.com/791320/46779339-b0b1e780-cd5a-11e8-85ec-ea5d97919f47.png)
![kybook-bookmark-2](https://user-images.githubusercontent.com/791320/46779343-b60f3200-cd5a-11e8-8483-e713d8d461be.png)

Please, at future, first try to use an suggested feature by yourself before reporting an issue.

**Comment by weiweihuanghuang** [comment]
Ah I realised it’s becuase I imported books from kybook 2 I didn’t see it
