### ISSUE TITLE
Hyphens are wrong

### ISSUE THREAD

**Issue by flopflip21** [kolyvan/kybook#76]
I have noticed that the hyphens on Kybook3 are not what is present in the font, no matter what font I change to, it shows a thin incorrect hyphen.

**Comment by flopflip21** [comment]
![2be32257-ae91-4da6-8190-c7e27ba44b0c](https://user-images.githubusercontent.com/11042561/46786504-cb975280-cd80-11e8-886a-c9af2728a9a1.png)
![073ceaaa-ad19-40aa-8777-8e0c653de1d5](https://user-images.githubusercontent.com/11042561/46786516-d6ea7e00-cd80-11e8-8c5b-b2b33a2bebde.png)


Here is photo of the incorrect hyphen in v3

**Comment by flopflip21** [comment]
![6a217044-3a53-4251-8299-b840a799307c](https://user-images.githubusercontent.com/11042561/46786559-f7b2d380-cd80-11e8-9655-c8971d91ac5e.png)
![dfe5ffd3-a36f-47b6-8edc-eeeb6290953b](https://user-images.githubusercontent.com/11042561/46786565-fb465a80-cd80-11e8-9186-fd40c2829ff3.png)

Correct hyphens in v2

**Comment by kolyvan** [comment]
Turn off the `Hanging punctuation` settings in the `Readability` section and obtain your "correct" hyphens.

![kybook-hyphens](https://user-images.githubusercontent.com/791320/46786721-0dbc9600-cd79-11e8-82b3-a78da9a6c9f3.png)
