### ISSUE TITLE
Lines start with punctuation that should not be at the start 

### ISSUE THREAD

**Issue by weiweihuanghuang** [kolyvan/kybook#77]
I noticed this started to happen in kybook 3, regardless of the font and book. I have hanging punctuation off and override book styles and no custom css 
![e2833549-c6a0-4045-ab78-f363bcec97c3](https://user-images.githubusercontent.com/1271897/46901448-b3017680-ceff-11e8-9ae2-fdbcba6ed009.png)

**Comment by kolyvan** [comment]
Already fixed in beta v0.5.6
