### ISSUE TITLE
Семейный доступ

### ISSUE THREAD

**Issue by VsVasi** [kolyvan/kybook#78]
Здравствуйте! Пользуюсь KyBook-2, версией Про на ipad. Недавно приобрел 2-й планшет ipad, на него через функцию Семейные покупки устанвил купленную версию, но она требует вновь покупки до версии про. при восстановлении покупки в самой программе выдается ошибка. На сайте App Store указано, что Семейные покупки поддерживаются. В чем может быть проблема?

**Comment by VsVasi** [comment]
Уточню: не семейные покупки, а Семейный доступ

**Comment by kolyvan** [comment]
Прочтите пожалуйста информацию от Apple

[support.apple.com/ru-ru/HT202023](https://support.apple.com/ru-ru/HT202023)
[support.apple.com/ru-ru/HT203046](https://support.apple.com/ru-ru/HT203046)

**Comment by VsVasi** [comment]
Я правильно понимаю, что приобретение лицензии до версии Про на моем планшете является Покупкой в программе, и этой покупкой нельзя делится в рамках семейного доступа? Я просто хочу этот вопрос уточнить, и если лицензию нельзя передать по семейному доступу, я ее приобрету на другом устройстве, т. к. другой альтернативе вашей программе нет.
