### ISSUE TITLE
Links in ePubs are broken

### ISSUE THREAD

**Issue by sebwin** [kolyvan/kybook#79]
Links in ePubs are inactve and rendered in red.

kybook 3 v.0.5.5 #98

**Comment by kolyvan** [comment]
> Links in ePubs are inactve

Which epub? Unfortunately without a file I can't say nothing.

> rendered in red.

What is wrong with red?

**Comment by sebwin** [comment]
Well, all epubs were affected.
But it turns out, you changed the link activation behavior from a simple tap in Kybook 2 to a tap & hold in Kybook 3. I only figured that out just now and links work flawlessly (unless the long tap instead selects text close to the tiny footnote link I’m trying to trigger…).

Red? Well, red is beautiful. I just took it for a sign of the links being inactive. My mistake. We should all use much more red! That said I like links in blue — for historical reasons, I guess.

**Comment by kolyvan** [comment]
> That said I like links in blue — for historical reasons, I guess.

Just change a theme, a link color is an attribute of a current theme.
