### ISSUE TITLE
Изменение местоположения кнопки "Размер текста"

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#8]
Кнопку «Размер текста» лучше вынести из диалога общих настроек на панель инструментов в режим чтения книги: Очень часто требуется при чтении изменять размер шрифта, и неудобно всякий раз переходить в общие настройки - много лишних движений.

**Comment by kolyvan** [comment]
Планировалось добавить возможность настраивать разметку (font family, text size, line height, paragraph indent, paragraph spacing, text align) отдельно для текста (вдобавок к глобальным  настройкам).

А  проблема в том что места для дополнительных кнопок на верхней панели нет.
Пока я ищу способ убрать с верхней панели кнопку для TTS (вынести TTS в меню по тапу), и возможно вместе нее добавить кнопку для настроек просмотра книги.
