### ISSUE TITLE
Suggest to add dropbox selective download

### ISSUE THREAD

**Issue by ghost** [kolyvan/kybook#81]

**Comment by kolyvan** [comment]
Sorry, but could You explain your suggestion in more details?

**Comment by ghost** [comment]
When I link a folder of the dropbox to kybook, kybook will automatically download the e-book in the folder after connecting to the network. I think this consumes a lot of space, choose the download option and download it better when needed.

**Comment by kolyvan** [comment]
KyBook need to know a title, author and other metadata of ebook to display them to an user.
Also KyBook must display a cover from an ebook on the card in a bookshelf.
There is no way to obtain such information without downloading a file from Cloud Storage (except audio book when Cloud Storage supports streaming, but this is not a general case).

>  I think this consumes a lot of space,

Yes, KyBook caches downloaded files and stores them in the special cache folder.
You can always free a disk space used by cache via the application settings.

**Comment by ghost** [comment]
Just like kybook2 only gets the necessary information such as the file name. If the dropbox associated with kybook3 has a 100g ebook, then it will download 100g, which is unnecessary.

发送自 Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by kolyvan** [comment]
1) KyBook 3 is not KyBook 2.

> If the dropbox associated with kybook3 has a 100g ebook

2) KyBook 3 downloads files only from the open folder, and it is unlikely that one folder has 100 gb ebook inside.
