### ISSUE TITLE
Pressing pause when using Auto-Scroll

### ISSUE THREAD

**Issue by Jfbowyer** [kolyvan/kybook#83]
Hi, First of all I should tell you that is far and away the best e-reading book reader app in the App Store. Thank you!

Second, when pressing pause at the bottom of the page when using Auto-Scroll, the auto-scroll goes away completely, instead of staying there waiting for me to press Play. So pressing pausing basically leaves the Auto-Scroll setting, and I have to then go back into the settings to restart Auto-Scroll. Is this the way the app is supposed to work? And if so do you think it may be changed so once you press the pause button in Auto-Scroll, it stays in Auto-Scroll mode waiting for you to hit that button again to start Auto-scrolling again?

Thank you!

James

**Comment by kolyvan** [comment]
Thank you for suggestion.

Unfortunately I do not plan to change the auto scrolling feature in the nearest future.
I completely satisfied with the current implementation of the auto scrolling.
