### ISSUE TITLE
BUG: Проблема разворота в pdf и djvu файлах

### ISSUE THREAD

**Issue by ysn-0711** [kolyvan/kybook#85]
До сих пор считаю Kybook лучшей читалкой и не только для iPada. Ho, верните, psl, функционал, который уже был в 1 и 2-ой версиях: возможность читать разворот книги в pdf и, если можно, djvu.
На iPad Pro нет пункта в меню для этих форматов.
Очень нужно для книг с таблицами на разворот. 
Пишу об этой проблеме уже после каждого из трех последних обновлений.

**Comment by kolyvan** [comment]
Дублирует #68
