### ISSUE TITLE
Wrong layout in horizontal view

### ISSUE THREAD

**Issue by NikitaKunashov** [kolyvan/kybook#86]
Steps to reproduce: 
1. Open a book in a horizontal layout. There are two pages are shown.
2. Disable the screen using the device button. Then rotate the device to the vertical position and unlock it. KyBook still shows two pages, but both of them are truncated.
![image](https://user-images.githubusercontent.com/23194319/47659509-2c5ac380-dba6-11e8-90c5-339c97072834.png)

**Comment by kolyvan** [comment]
Thank you very much for reporting about this bug.
Temporary fix: rotate a device and return back for fixing.  
I will address this issue someday.

**Comment by kolyvan** [comment]
Fixed in v0.6.0
