### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by ecleere** [kolyvan/kybook#87]
Hi,

I'm trying to create a new dark theme, but I can't seem to choose a full black background, (eg. #000000 or RGB(000) ). This would be similar to the default 'Night' theme, but the pallet doesn't seem to have full black?

Thanks,
Ed

**Comment by kolyvan** [comment]
Just enter the RGB #000000 manually into a color value text field.

![kybook-pallete](https://user-images.githubusercontent.com/791320/47694321-ec98e800-dc48-11e8-8b05-ca9a530c7e55.png)

**Comment by ecleere** [comment]
Cool, thanks!
