### ISSUE TITLE
FR: Please add parsing of HTML in annotations

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#89]
Some book notes/comments contain HTML. It would be useful if KyBook 3 could parse these where they appear.

**Comment by kolyvan** [comment]
Sorry but your FR is not compatible with the current design.

**Comment by karlic** [comment]
For anybody else wanting this because their books come from Calibre, I now have a script that syncs from Calibre to KyBook 3 and strips out the html.

**Comment by karlic** [comment]
The script is now also a Calibre plugin available here https://www.mobileread.com/forums/showthread.php?t=316347
