### ISSUE TITLE
Добавить кнопку Отмена в диалог редактирования метаданных книги

### ISSUE THREAD

**Issue by DikBSD** [kolyvan/kybook#9]
Добавить в диалог изменения метаданных кнопку ОТМЕНА. Сейчас приходится восстанавливать те данные описания книги, которые изменил или случайно изменил, иначе по "Готово" они вольются в базу. А было бы удобнее просто нажать кнопку Отмена.

**Comment by kolyvan** [comment]
Наверно правильно добавить такую возможность, но с другой стороны насколько часто и насколько многим пользователям это необходимо? И стоит ли городить огород (тестирование, неизбежные баги) для фичи которую дай бог заюзают несколько продвинутых пользователей раз в год?
