### ISSUE TITLE
FR: Add the ability to remove books from Reading now

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#90]
I transfer a book to KyBook3.
Open it for 1 second to check all is OK
The book stays in Reading now for weeks.

It would be nice to be able to remove it from Reading now. (Or maybe only add books that have been read for a minimum of, say, 5 minutes?)

I suspect the functionality to do this would overlap with https://github.com/kolyvan/kybook/issues/37

**Comment by agmalis** [comment]
I would also like this feature. I have a lot of books that I've never even opened that for some reason are in the "Reading" category in the Cataloguer. I would like to be able to move them to the "Unread" category. Thanks! This is Kybook 3 v0.6.1 #115 on iOS 12.1.

**Comment by kolyvan** [comment]
Done in beta v0.6.3

**Comment by agmalis** [comment]
Thanks, much appreciated!
