### ISSUE TITLE
Delete from database + mirrored

### ISSUE THREAD

**Issue by tsroman** [kolyvan/kybook#97]
Deleting book from database still keep them in Mirrored storage.
I'm using SMB share to sync my EPUB books with device and PC. And when I change my book I need to redownload it from storage, manually delete from database + clear mirrored.
Can you please make this as one action, a book should delete completely, including Mirrored.

Ideally, kybook should detect changes in the original file and do it automatically.

**Comment by kolyvan** [comment]
> Can you please make this as one action, a book should delete completely, including Mirrored.

Yes, it seems reasonable suggestion. I will implement it the next release.

> Ideally, kybook should detect changes in the original file and do it automatically.

Sorry, but automatic detection of changes on the cloud storage for every file is too cost, especially for a mobile device working from the battery.

**Comment by kolyvan** [comment]
Fixed on beta v0.6.3
