### ISSUE TITLE
What is the best way to back up notes?

### ISSUE THREAD

**Issue by gety9** [kolyvan/kybook#98]
Konstantin hi,

It's not an issue, but more a question - what is the best way to back up notes? 
Recently my iphone 7 died and with it 3 months of notes i've made.
So i would like to have possibility to back up notes to cloud.

p.s. I am using Kybook 2 on iphone.

**Comment by kolyvan** [comment]
Replied on the forum http://disq.us/p/1xop3i9 

Please use the forum for trivia questions.
