### ISSUE TITLE
Change the interface language

### ISSUE THREAD

**Issue by rudolf-bauer** [kolyvan/kybook#99]
Hi,

I have two iOS devices. On the iPhone kybook3 works like a charm. However, on the new iPad it's in Russian and I have no idea how to change it. :)

Best wishes,
Rudi

**Comment by kolyvan** [comment]
At this moment the release version of KyBook has localized for 3 languages: English (default), Russian and Spanish. 

If you have the interface in `Russian`, there are only two possible options:
- You selected `Russian` as your primary iOS language in the `iOS Language & Region` settings.
- Or you have `Russian` in the `iOS Preferred language` list and and there is no `English` in the `iOS Preferred language` list.

In both cases, you perhaps manually added `Russian` as your preferred language in the iOS language settings.
Please check your iOS settings -> General -> Language & Region -> Preferred language list and or remove `Russian` from the list or add `English` to the list.

![ios-lang-settings](https://user-images.githubusercontent.com/791320/49124639-ea3db280-f308-11e8-9ba1-7dfb683e89ab.png)
